# syntax=docker/dockerfile:1

FROM golang:1.25 AS builder

WORKDIR /src

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server ./cmd/velocity-api

FROM gcr.io/distroless/base-debian11

COPY --from=builder /app/server /app/server

CMD ["/app/server"]
